pi@raspberrypi:~/mirai/QQreboot-Mirai-Graia $ python3 bot.py 
[Log] load img model done!
[2020-11-21 20:40:21,150][INFO]: initializing app...
[2020-11-21 20:40:21,228][INFO]: detecting remote's version...
[2020-11-21 20:40:21,242][INFO]: detected remote's version: 1.8.4
[2020-11-21 20:40:21,259][INFO]: using pure websocket to receive event
[2020-11-21 20:40:21,260][INFO]: found websocket disabled, so it has been enabled.
[2020-11-21 20:40:21,277][INFO]: event receive method checked.
[2020-11-21 20:40:21,278][INFO]: this application's initialization has been completed.
[2020-11-21 20:40:21,279][INFO]: --- setting start ---
[2020-11-21 20:40:21,280][INFO]: broadcast using: <graia.broadcast.Broadcast object at 0x6b7e1a70>
[2020-11-21 20:40:21,281][INFO]: enable log of chat: yes
[2020-11-21 20:40:21,282][INFO]: debug: no
[2020-11-21 20:40:21,283][INFO]: version(remote): 1.8.4
[2020-11-21 20:40:21,284][INFO]: --- setting end ---
[2020-11-21 20:40:21,285][INFO]: application has been initialized, used 0.134s




^C[2020-11-21 20:42:35,514][INFO]: application shutdowned.
Traceback (most recent call last):
  File "bot.py", line 230, in <module>
    app.launch_blocking()
  File "/home/pi/.local/lib/python3.7/site-packages/graia/application/__init__.py", line 1091, in launch_blocking
    loop.run_until_complete(self.getFetching()())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
